// Auto-generated by wrangler types --env-interface CloudflareBindings
// Do not edit manually. Regenerate with: bun run types

interface CloudflareBindings {
  DB: D1Database;
  BETTER_AUTH_URL: string;
  BETTER_AUTH_SECRET: string;
}
